const CONFIG = {
    titleWeb: "HELLU!!",
    introTitle: 'GỬI TẶNG CẢ NHÀ',
    introDesc: `Đến từ một người dễ thưn bí ẩn tên T.`,
    btnIntro: '^^HiHi^^',
    title: 'Trả lời thành thật nha 🥰',
    desc: 'Mọi ngừi có ghét T. không? ',
    btnYes: 'Ghét chết đi đc <33',
    btnNo: 'Không nha :3',
    question: 'Huhu tại sao mn lại không iu quý T. <3',
    btnReply: 'Gửi nè <3',
    reply: 'Haha đùa thui T. dễ thưn mà <33333333',
    mess: ' Biết mà hihi🥰. Yêu mn nhiều nhiều 😘😘',
    messDesc: 'HAPPY NEW YEAR!!. Mọi người đã rất cố gắng trong suốt cả năm vừa qua rồi. Chúc cho cả nha mình lun dễ thưn và năng suất hơn trong năm mới nữa ha hmihmi:>>',
    btnAccept: 'Quạc Quạc<3',
    messLink: 'https://www.youtube.com/watch?v=zQZ2WVRKPbA',
}
